import Navbar from "@/components/common/Navbar";
import "./globals.css";
import { Inter, Nunito } from "next/font/google";

const inter = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-light text-dark w-full min-h-screen px-8 md:px-16 lg:px-32 2xl:px-40`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
